# Generated by Django 4.2.2 on 2023-06-30 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0003_colaborador_empresa'),
        ('registro_hora_extra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrohoraextra',
            name='colaborador',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='funcionarios.colaborador'),
        ),
    ]
