# Generated by Django 4.2.2 on 2023-06-30 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('funcionarios', '0002_colaborador_departamentos_colaborador_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='empresa',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='empresas.empresa'),
        ),
    ]
