# Generated by Django 4.2.2 on 2023-07-01 15:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro_hora_extra', '0002_registrohoraextra_colaborador'),
        ('departamentos', '0001_initial'),
        ('documentos', '0003_alter_documentos_pertence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empresas', '0001_initial'),
        ('funcionarios', '0004_alter_colaborador_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Colaborador',
            new_name='Funcionario',
        ),
    ]
